#!/bin/sh
# Pre-commit hook: auto-update version timestamp in index.html

DATESTAMP=$(date "+%b %-d, %Y %-I:%M %p")

sed -i "s|\(id=\"landing-version\">v[0-9.]* &mdash; \).*\(</div>\)|\1${DATESTAMP}\2|" index.html

git add index.html
